# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemv7.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='itemv7.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0citemv7.proto\"_\n\x13\x45ncryptedSecretData\x12\x12\n\nciphertext\x18\x01 \x02(\x0c\x12\x1f\n\nwrappedKey\x18\x02 \x02(\x0b\x32\x0b.WrappedKey\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t\".\n\nWrappedKey\x12\x12\n\nwrappedKey\x18\x01 \x02(\x0c\x12\x0c\n\x04type\x18\x03 \x02(\r\"P\n\x11\x45ncryptedMetadata\x12\x12\n\nciphertext\x18\x01 \x02(\x0c\x12\x12\n\nwrappedKey\x18\x02 \x02(\x0c\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t\"\x84\x01\n\x0eItemV7Protobuf\x12\x31\n\x13\x65ncryptedSecretData\x18\x01 \x02(\x0b\x32\x14.EncryptedSecretData\x12-\n\x11\x65ncryptedMetadata\x18\x02 \x02(\x0b\x32\x12.EncryptedMetadata\x12\x10\n\x08keyclass\x18\x03 \x02(\x05')
)




_ENCRYPTEDSECRETDATA = _descriptor.Descriptor(
  name='EncryptedSecretData',
  full_name='EncryptedSecretData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='EncryptedSecretData.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='EncryptedSecretData.wrappedKey', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='EncryptedSecretData.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=111,
)


_WRAPPEDKEY = _descriptor.Descriptor(
  name='WrappedKey',
  full_name='WrappedKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='WrappedKey.wrappedKey', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='WrappedKey.type', index=1,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=159,
)


_ENCRYPTEDMETADATA = _descriptor.Descriptor(
  name='EncryptedMetadata',
  full_name='EncryptedMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='EncryptedMetadata.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='EncryptedMetadata.wrappedKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='EncryptedMetadata.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=241,
)


_ITEMV7PROTOBUF = _descriptor.Descriptor(
  name='ItemV7Protobuf',
  full_name='ItemV7Protobuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryptedSecretData', full_name='ItemV7Protobuf.encryptedSecretData', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encryptedMetadata', full_name='ItemV7Protobuf.encryptedMetadata', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyclass', full_name='ItemV7Protobuf.keyclass', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=376,
)

_ENCRYPTEDSECRETDATA.fields_by_name['wrappedKey'].message_type = _WRAPPEDKEY
_ITEMV7PROTOBUF.fields_by_name['encryptedSecretData'].message_type = _ENCRYPTEDSECRETDATA
_ITEMV7PROTOBUF.fields_by_name['encryptedMetadata'].message_type = _ENCRYPTEDMETADATA
DESCRIPTOR.message_types_by_name['EncryptedSecretData'] = _ENCRYPTEDSECRETDATA
DESCRIPTOR.message_types_by_name['WrappedKey'] = _WRAPPEDKEY
DESCRIPTOR.message_types_by_name['EncryptedMetadata'] = _ENCRYPTEDMETADATA
DESCRIPTOR.message_types_by_name['ItemV7Protobuf'] = _ITEMV7PROTOBUF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncryptedSecretData = _reflection.GeneratedProtocolMessageType('EncryptedSecretData', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDSECRETDATA,
  __module__ = 'itemv7_pb2'
  # @@protoc_insertion_point(class_scope:EncryptedSecretData)
  ))
_sym_db.RegisterMessage(EncryptedSecretData)

WrappedKey = _reflection.GeneratedProtocolMessageType('WrappedKey', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPEDKEY,
  __module__ = 'itemv7_pb2'
  # @@protoc_insertion_point(class_scope:WrappedKey)
  ))
_sym_db.RegisterMessage(WrappedKey)

EncryptedMetadata = _reflection.GeneratedProtocolMessageType('EncryptedMetadata', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDMETADATA,
  __module__ = 'itemv7_pb2'
  # @@protoc_insertion_point(class_scope:EncryptedMetadata)
  ))
_sym_db.RegisterMessage(EncryptedMetadata)

ItemV7Protobuf = _reflection.GeneratedProtocolMessageType('ItemV7Protobuf', (_message.Message,), dict(
  DESCRIPTOR = _ITEMV7PROTOBUF,
  __module__ = 'itemv7_pb2'
  # @@protoc_insertion_point(class_scope:ItemV7Protobuf)
  ))
_sym_db.RegisterMessage(ItemV7Protobuf)


# @@protoc_insertion_point(module_scope)
